GameItems/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .account.urls import urlpatterns as account_urls
from .core.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^account/', include((account_urls, 'account'), namespace='account')),
    url(r'^$', HomePage.as_view(),name='homepage'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/account/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView,\
                                       PasswordResetConfirmView, PasswordResetCompleteView 

from .views import LoginView, RegisterView, UpdateAddress

urlpatterns = [
    
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^register/$', RegisterView.as_view(),name='register'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^updateaddress/$', UpdateAddress.as_view(),name='updateaddress'),
    url(r'^password_reset/$',
        PasswordResetView.as_view(template_name='password/forgot-password.html',
                                  success_url=reverse_lazy('account:password_reset_done')),
                                  name='password_reset'),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html',
                                         success_url = reverse_lazy('account:password_reset_complete')),
                                        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
]

eCommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .account.urls import urlpatterns as account_urls
from .products.urls import urlpatterns as product_urls
from .carts.urls import urlpatterns as cart_urls
from .orders.urls import urlpatterns as order_urls

from .core.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage.as_view(),name='homepage'),
    
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^order/', include(order_urls, namespace='order')),
    
]

handler404 = 'eCommerce.views.page_not_found_custom'    
handler500 = 'eCommerce.views.page_error_found_custom' 

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from .utils import ADDRESS_TYPE, STATE_MAPPING


class AccountManager(models.Manager):
    
    def create_account(self,user,first_name,last_name,email):
        return self.create(user=user,first_name=first_name, last_name=last_name, email=email)
    
    def get_account_by_id(self,account_id):
        return self.filter(id=id)
    
    def get_account_by_user(self,user_id):
        return self.filter(user_id=user_id)
    
class Account(models.Model):
    user                  = models.OneToOneField(User)
    first_name            = models.CharField(max_length=50,default='')
    last_name             = models.CharField(max_length=50,default='')
    email                 = models.EmailField(max_length=250)
    phone_regex           = RegexValidator(regex=r'^\+91[7-9]\d{9}$')
    phone_number          = models.CharField(validators=[phone_regex], max_length=17, null=True) 
    created_by            = models.CharField(max_length=50, default='account')
    created_datetime      = models.DateField(auto_now_add=True)
    modified_by           = models.CharField(max_length=50, default='')
    modified_datetime     = models.DateField(null=True,auto_now=True)
    
    objects               = AccountManager()
    def __str__(self):
        return self.user.username


class AccountAddressManager(models.Manager):
    
    def seacrh_address_by_account(self,account_id):
        return self.filter(account_id=account_id)
    
    def update_address(self,username,address_details):
        user            = User.objects.filter(username=username)
        account         = Account.objects.get_account_by_user(user.first().id)
        account_address = self.seacrh_address_by_account(account.first().id)
        if account_address:
            self.update(first_name=address_details.get('first_name'),last_name=address_details.get('last_name'),
                        phone_number=address_details.get('phone_number'),
                        building_info=address_details.get('building_info'),area=address_details.get('area'),
                        city=address_details.get('city'),pincode=address_details.get('pincode'),
                        state=address_details.get('state'),address_type=address_details.get('address_type'))
        else:
            self.create(account=account.first(),first_name=address_details.get('first_name'),last_name=address_details.get('last_name'),
                        phone_number=address_details.get('phone_number'),
                        building_info=address_details.get('building_info'),area=address_details.get('area'),
                        city=address_details.get('city'),pincode=address_details.get('pincode'),
                        state=address_details.get('state'),address_type=address_details.get('address_type'))
            

class AccountAddress(models.Model):
    """
    Will have one is to one relation with account for now.
    Whenever customer chnages the address we update with the new one
    """
    account               = models.OneToOneField(Account)
    first_name            = models.CharField(max_length=50)
    last_name             = models.CharField(max_length=50)
    phone_regex           = RegexValidator(regex=r'^\+91[7-9]\d{9}$')
    phone_number          = models.CharField(validators=[phone_regex], max_length=17, null=True) 
    building_info         = models.CharField(max_length=500,default='')
    area                  = models.CharField(max_length=500,default='')
    city                  = models.CharField(max_length=50,default='')
    pincode               = models.PositiveIntegerField()
    state                 = models.CharField(max_length=100,choices=STATE_MAPPING)
    address_type          = models.CharField(max_length=25,default='home',choices = ADDRESS_TYPE)
    objects               = AccountAddressManager()
    
    def __str__(self):
        return str(self.account.id)

eCommerce/account/views.py
import json

from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django import db
from django.views import View
from django.shortcuts import render, redirect, HttpResponse
from django.utils.http import is_safe_url

from ..carts.backend.backend import CartBackend

from .models import Account, AccountAddress

class AccountBaseClass(View):
    def __init__(self):
        self.account_obj = Account.objects

        
class LoginView(AccountBaseClass):
    
    """Login page View"""
    
    def get(self,request):
        """Replace the code, added to test"""
        try:
            return render(request,'login.html',{})
        except:
            pass
        
    def post(self,request):
        
        """
        Authenticate and log in a user and redirect him to the home page.
        If not authenticated reload the pgae with error in the context dict
        """
    
        try:
            username     = request.POST['email']
            password     = request.POST['password']
            next_        = request.GET.get('next')
            next_post    = request.POST.get('next')
            next_url     = next_ or next_post
            user = authenticate(request, username=username, password=password)
            if user is not None:
                CartBackend().updateCartWithUser(user, request.session.get('cart_id'))
                login(request, user)
                """Also set the userid and account id in session so that we dont have to make db
                calls for these details"""
                if is_safe_url(next_url, request.get_host()):
                    redirect(next_url)
                else:
                    return redirect("/")
            else:
                return render(request,'login.html',{'invalid_user':True})
        except:
            print('500') 

class RegisterView(AccountBaseClass):
    """
    View to Register a User
    """
    
    def post(self,request):
        """
        Create an User
        """
        first_name  = request.POST.get('first_name')
        last_name   = request.POST.get('last_name')
        password    = request.POST.get('password')
        email       = request.POST.get('email_id')
        """
        can keep username as the emailid. Can think of some other logic
        or maybe can do an ajax call while entering username to check if it already exists.
        Also can create user based on either email or mobile
        """
        try:
            user = User.objects.create_user(email, email, password)
            if user:
                """
                Login him and redirect to the login Page. Send account Activation Mailer??
                Also set the userid and account id in session so that we dont have to make db
                calls for these details
                """
                login(request, user)
                self.account_obj.create_account(user ,first_name, last_name, email)
                return redirect('/')
        except db.IntegrityError:
            return render(request,'login.html',{'user_exists':True})
        except Exception as ex:
            print("500::"+ex.message)   
            

class UpdateAddress(AccountBaseClass):
    
    """
        View to update the address for an account
    """
    
    def post(self,request):
        try:
            address_obj     = AccountAddress.objects
            address_details = request.POST
            address_obj.update_address(request.user,address_details)
            response = {'response':True} 
        except:
            response = {'response':False}
        return HttpResponse(json.dumps(response), content_type="application/json")
            

eCommerce/account/templates/login.html
{% extends 'base.html'%}
{% load static %}
{% block content%}
    <div id="all">

        <div id="content">
            <div class="container">

                <div class="col-md-6">
                    <div class="box">
                        <h1>New account</h1>

                        <p class="lead">Not our registered customer yet?</p>
                        <!-- <p>With registration with us new world of fashion, fantastic discounts and much more opens to you! The whole process will not take you more than a minute!</p>
                        <p class="text-muted">If you have any questions, please feel free to <a href="contact.html">contact us</a>, our customer service center is working for you 24/7.</p>-->
                        {% if user_exists %}
                        	<div class="alert alert-danger" role="alert">
								  Email already exists !
							</div>
						{% endif %}	
                        <hr>

                        <form action="{% url 'account:register' %}" method="post" id="register_form">{% csrf_token %}
                            <div class="form-group">
                                <label for="name">First Name</label>
                                <input type="text" class="form-control" id="first_name" name="first_name">
                            </div>
                            <div class="form-group">
                                <label for="name">Last Name</label>
                                <input type="text" class="form-control" id="last_name" name="last_name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email_id" name="email_id">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password">
                            </div>
                            <div class="form-group">
                                <label for="password">Confirm Password</label>
                                <input type="password" class="form-control" id="confirm_password" name="confirm_password">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-user-md"></i> Register</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="box">
                        <h1>Login</h1>

                        <p class="lead">Already our customer?</p>
							{% if invalid_user%}
								<div class="alert alert-danger" role="alert">
								  Username or password does not match !
								</div>
							{% endif %}			
                        <hr>

                        <form action="{% url 'account:login' %}" method="post" id="login_form">{% csrf_token %}
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" class="form-control" id="email" name="email">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                                <br>
                                <p class="text-center text-muted"><a href="{% url 'account:password_reset' %}"><strong>Forgot Password?</strong></a>
                            </div>
                        </form>
                    </div>
                </div>


            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->


{% endblock content%}

{% block jqueryblock%}
	<script>
		$('#register_form').validate({
			errorClass			:	"error-class",
			rules:{
				first_name		:	"required",
 				last_name		:	"required",
 				email_id		:	"required",
 				password		:{
 									required:true,
 									password:true
 								 },
 				confirm_password: "#password"
			},
			messages:{
				first_name		: 	"Please enter a valid first name",
 				last_name		: 	"Please enter a valid last name",
 				email_id		:	"Please enter a valid email id",
 				password		:{
 									required: "Please enter a password",
 									password: "Please enter a valid password"
 								 },
 				confirm_password:	"Passwords does not match"
			}
		});
	</script>
{% endblock jqueryblock%}