GameItems/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .account.urls import urlpatterns as account_urls
from .core.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^account/', include((account_urls, 'account'), namespace='account')),
    url(r'^$', HomePage.as_view(),name='homepage'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/account/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView,\
                                       PasswordResetConfirmView, PasswordResetCompleteView 

from .views import LoginView, RegisterView, UpdateAddress

urlpatterns = [
    
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^register/$', RegisterView.as_view(),name='register'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^updateaddress/$', UpdateAddress.as_view(),name='updateaddress'),
    url(r'^password_reset/$',
        PasswordResetView.as_view(template_name='password/forgot-password.html',
                                  success_url=reverse_lazy('account:password_reset_done')),
                                  name='password_reset'),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html',
                                         success_url = reverse_lazy('account:password_reset_complete')),
                                        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
]

eCommerce/carts/urls.py
from django.conf.urls import url

from .views import UpdateCart, CartView, GetCartCount

urlpatterns = [
    url(r'^$', CartView.as_view(),name='cartview'),
    url(r'^updatecart/$', UpdateCart.as_view(),name='updatecart'),
    url(r'^cartcount/$', GetCartCount.as_view(),name='cartcount'),
]

eCommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .account.urls import urlpatterns as account_urls
from .products.urls import urlpatterns as product_urls
from .carts.urls import urlpatterns as cart_urls
from .orders.urls import urlpatterns as order_urls

from .core.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage.as_view(),name='homepage'),
    
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^order/', include(order_urls, namespace='order')),
    
]

handler404 = 'eCommerce.views.page_not_found_custom'    
handler500 = 'eCommerce.views.page_error_found_custom' 

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/carts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
# Create your models here.
from math import fsum
from eCommerce.products.models import Product


class CartManager(models.Manager):
    
    def create_cart_obj(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)
    
    def get_cart_by_id(self,cart_id):
        return self.get_queryset().filter(id=cart_id)
    
    def get_cart_by_user(self,user):
        user_id = User.objects.filter(username=user)
        return self.filter(user_id=user_id)
    
    def get_or_create_cart(self,request):
        cart_id = request.session.get('cart_id',None)
        qs = self.get_cart_by_id(cart_id)
        if qs.count()==1:
            cart_obj = qs.first()
            if request.user.is_authenticated() and not cart_obj.user:
                cart_obj.user = request.user
                cart_obj.save()
                request.session['cart_id'] = cart_obj.id
        else:        
            cart_obj = self.create_cart_obj(request.user)
            request.session['cart_id'] = cart_obj.id
        return cart_obj    
    
            
class Cart(models.Model):
    """
    Cart Model
    Create one more table to store the product quantity in cart.
    Should have a foreign key to cart and for each product in cart will have a
    record having the quantity.
    """
    user                = models.ForeignKey(User, null =True, blank=True)
    subtotal            = models.DecimalField(max_digits=7,decimal_places=2,default=0.00)
    total               = models.DecimalField(max_digits=7,decimal_places=2,default=0.00)
    created_datetime    = models.DateField(auto_now_add=True)
    modified_datetime   = models.DateField(auto_now=True)
    
    objects             = CartManager()
    
    def __str__(self):
        return str(self.id)

    
class CartDetailsManager(models.Manager):
    
    def get_cart_details(self,cart_id,product_id):
        return self.filter(product_id=product_id,cart_id=cart_id)        
    
    def create_cart_details(self,cart,product):
        return self.create(cart=cart,product=product,price=product.price )
    
    def get_cart_count(self,cart_id):
        return self.get_queryset().filter(cart_id=cart_id).count()    
    
    def get_cart_items(self,cart_id):
        return self.get_queryset().filter(cart_id=cart_id)
    
    
class CartDetails(models.Model):
    cart                = models.ForeignKey(Cart)
    product             = models.ForeignKey(Product)
    price               = models.DecimalField(max_digits=7,decimal_places=2,default=0.00)
    quantity            = models.IntegerField(default=1)
    total               = models.DecimalField(max_digits=7,decimal_places=2,default=0.00)
    created_datetime    = models.DateField(auto_now_add=True)
    modified_datetime   = models.DateField(auto_now=True)
    
    objects             = CartDetailsManager()
    
    def __str__(self):
        return str(self.cart_id)


"""
    Signals to update the total and subtotal in the Cart
"""    
def post_save_cart_details_receiver(sender,instance,*args,**kwargs):
    """
    Add the extraCharges Method to take into consideration
    the shipping charges and taxes
    """
    cart_details_obj = CartDetails.objects.filter(cart_id=instance.cart_id)
    if cart_details_obj:
        total = 0
        for cart in cart_details_obj:
            total = fsum([total,cart.price*cart.quantity])
            CartDetails.objects.filter(cart_id=instance.cart_id,product_id=cart.product_id).update(total=cart.price*cart.quantity)
        Cart.objects.filter(pk=instance.cart_id).update(subtotal=total,total=total)
            
post_save.connect(post_save_cart_details_receiver, sender=CartDetails)   
post_delete.connect(post_save_cart_details_receiver, sender=CartDetails)                   

eCommerce/carts/views.py
import json

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views import View
from django.http.response import HttpResponse

from .models import Cart, CartDetails
from ..products.models import Product

# Create your views here.
class CartsBaseView(View):
        
        def __init__(self):
            self.context        = {}
            self.cart_obj       = Cart.objects
            self.cart_det_obj   = CartDetails.objects

class CartView(CartsBaseView):
    
    def get(self,request):
        """
        View to show the cart page. Get the products in the cart base on whether the user is
        logged in or not.
        Think about the idea when user is logged in and not logged in.
        """
        try:
            if request.user.is_authenticated():
                cart = self.cart_obj.get_cart_by_user(request.user)
            else:
                cart = self.cart_obj.get_cart_by_id(request.session.get('cart_id',None))
            
            if not cart:
                self.context['no_items'] = True
                return  render(request, 'cart.html', self.context)
            request.session['cart_id'] = cart.first().id
            cart_details_list =[]
            if cart:
                cart_details = self.cart_det_obj.get_cart_items(cart.first().id) 
                """ 
                :Note If face any issue with cart order by cartid and get the latest cartid.
                """
                for cart in cart_details:
                    product = Product.objects.filter(id=cart.product_id)
                    cart_temp_dict = {}
                    cart_temp_dict['product']       = product.first()
                    cart_temp_dict['quantity']      = cart.quantity
                    cart_temp_dict['price']         = product.first().price
                    cart_temp_dict[cart.id]         = cart.id
                    cart_details_list.append(cart_temp_dict)
                    
                self.context['cart_details'] = cart_details_list
                self.context['cart_count'] = cart_details.count()
            response = render(request, 'cart.html', self.context)
            return response
        except:
            print("500")
            raise Exception    
            
    def post(self,request):
        return redirect(reverse('order:orderview'))
    
    
class UpdateCart(CartsBaseView):
    """
    This the view which will get called on every addition or removal of
    product in the cart. Will update the cart based on the product id recieved from
    request
    """
    def post(self,request):
        try:
            product_id      = int(request.POST.get('product_id'))
            quantity        = request.POST.get('quantity')
            remove_product  = request.POST.get('remove_product')
            if product_id:
                if not remove_product: # Adding a product to cart
                    product_obj = Product.objects.get_product_by_id(product_id)
                    if not product_obj:
                        raise Product.DoesNotExist
                    cart = self.cart_obj.get_or_create_cart(request)
                    cart_detail_obj = self.cart_det_obj.get_cart_details(cart.id,product_id)
                    if cart_detail_obj:
                        if quantity:
                            cart_detail_obj.first().quantity = quantity
                            cart_detail_obj.first().save()
                        else:
                            cart_detail_obj.first().quantity = cart_detail_obj.first().quantity+1
                            cart_detail_obj.first().save()
                    else:                                         #and product id update the quantity only
                        self.cart_det_obj.create_cart_details(cart,product_obj)#Else this the first time product is being added
                    return redirect("/")
                else: # For removing the product from the cart                    #Create an entry in cart details object
                    cart_detail_obj = self.cart_det_obj.get_cart_details(request.session.get('cart_id'),product_id)
                    cart_detail_obj.delete()
                    cart_count =  self.cart_det_obj.get_cart_count(request.session.get('cart_id')) 
                    return HttpResponse(json.dumps({'cart_count': cart_count}), content_type="application/json")     
        except Product.DoesNotExist:
            pass
        except Exception as e:
            print("There was an issue updating the cart::%s" %(e.message))
            pass


class GetCartCount(CartsBaseView):
     
    def get(self,request):
        cart_id = request.session.get('cart_id')
            
        if request.user.is_authenticated():
            cart = self.cart_obj.get_cart_by_user(request.user)
        else:
            cart = self.cart_obj.get_cart_by_id(cart_id)
        cart_count = self.cart_det_obj.filter(cart_id=cart.first().id).count() if cart else 0
        return HttpResponse(json.dumps({'cart_count': cart_count}), content_type="application/json")

eCommerce/carts/templates/cart.html
{% extends 'base.html'%}
{% load static %}
{% block content%}

    <div id="all">

        <div id="content">
            <div class="container">

               <!--  <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a>
                        </li>
                        <li>Shopping cart</li>
                    </ul>
                </div> -->

                <div class="col-md-9" id="basket">

                    <div class="box">

                        <form method="post" action="{% url 'cart:cartview' %}"> {% csrf_token %}

                            <h1>Shopping cart</h1>
                            <p class="text-muted">You currently have {% if no_items %} 0 {% else %}{{cart_count}}{% endif %} item(s) in your cart.</p>
                            <div class="table-responsive">
                                <table class="table" id="cart_table">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Product</th>
                                            <th>Quantity</th>
                                            <th>Unit price</th>
                                            <th>Discount</th>
                                            <th colspan="2">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for cart in cart_details %}
                                        <tr id="{{cart.product.id}}">
                                            <td>
                                                <a href="{{cart.product.get_absolute_url}}">
                                                    <img src="{{cart.product.image.url}}" alt="{{cart.product.name}}">
                                                </a>
                                            </td>
                                            <td><a href="{{cart.product.get_absolute_url}}">{{cart.product.name}}</a>
                                            </td>
                                            <td>
                                                <input type="number" min="0" value="{{cart.quantity}}" class="form-control cart_quant">
                                            </td>
                                            <td class="td_cart_price">&#8377;{{cart.price}}</td>
                                            <td>&#8377;0.00</td>
                                            <td>&#8377;{{cart.price}}</td>
                                            <td><a class="trash_btn" data-value="{{cart.product.id}}"><i class="fa fa-trash-o"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th colspan="5">Total</th>
                                            <th colspan="2" class="cart_total"></th>
                                        </tr>
                                    </tfoot>
                                </table>

                            </div>
                            <!-- /.table-responsive -->

                            <div class="box-footer">
                                <div class="pull-left">
                                    <a href="/" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                                </div>
                                <div class="pull-right">
                                	{% if request.user.is_authenticated %}
                                    <button type="submit" class="btn btn-primary">Proceed to checkout <i class="fa fa-chevron-right"></i></button>
                                   	{% else %}
                                   	<a class="btn btn-primary" href="{% url 'account:login' %}?next={% url 'cart:cartview'%}">Login to checkout <i class="fa fa-chevron-right"></i></a>
                                    {% endif %}
                                    
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- /.box -->


                    <div class="row same-height-row">
                        <div class="col-md-3 col-sm-6">
                            <div class="box same-height">
                                <h3>You may also like these products</h3>
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-6">
                            <div class="product same-height">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="detail.html">
                                                <img src="img/product2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="detail.html">
                                                <img src="img/product2_2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="detail.html" class="invisible">
                                    <img src="img/product2.jpg" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3>Fur coat</h3>
                                    <p class="price">$143</p>
                                </div>
                            </div>
                            <!-- /.product -->
                        </div>

                        <div class="col-md-3 col-sm-6">
                            <div class="product same-height">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="detail.html">
                                                <img src="img/product1.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="detail.html">
                                                <img src="img/product1_2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="detail.html" class="invisible">
                                    <img src="img/product1.jpg" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3>Fur coat</h3>
                                    <p class="price">$143</p>
                                </div>
                            </div>
                            <!-- /.product -->
                        </div>


                        <div class="col-md-3 col-sm-6">
                            <div class="product same-height">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="detail.html">
                                                <img src="img/product3.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="detail.html">
                                                <img src="img/product3_2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="detail.html" class="invisible">
                                    <img src="img/product3.jpg" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3>Fur coat</h3>
                                    <p class="price">$143</p>

                                </div>
                            </div>
                            <!-- /.product -->
                        </div>

                    </div>


                </div>
                <!-- /.col-md-9 -->

                <div class="col-md-3">
                    <div class="box" id="order-summary">
                        <div class="box-header">
                            <h3>Order summary</h3>
                        </div>
                        <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Order subtotal</td>
                                        <th class="cart_total"></th>
                                    </tr>
                                    <tr>
                                        <td>Shipping and handling</td>
                                        <th>&#8377;0.00</th>
                                    </tr>
                                    <tr>
                                        <td>Tax</td>
                                        <th>$0.00</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th class="cart_total"></th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>


                    <div class="box">
                        <div class="box-header">
                            <h4>Coupon code</h4>
                        </div>
                        <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
                        <form>
                            <div class="input-group">

                                <input type="text" class="form-control">

                                <span class="input-group-btn">

					<button class="btn btn-primary" type="button"><i class="fa fa-gift"></i></button>

				    </span>
                            </div>
                            <!-- /input-group -->
                        </form>
                    </div>

                </div>
                <!-- /.col-md-3 -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->

{% endblock content %}

{% block javascriptblock %}
	<script>
	$(document).ready(function(){
		calculate_total();
	});
	
	$('.trash_btn').on('click',function(){
		 data={};
		 var product_id = $(this).data("value");
		data['remove_product'] =true;
		data['product_id'] = product_id;
		$.ajax({
		    url: "{% url 'cart:updatecart' %}",
		    type: "POST",
		    cache:false,
		    data: data,
		    dataType: "json",
		    success: function(resp){
		       $('#'+product_id).remove();
		       $('.cart_count').text(resp.cart_count);
		       calculate_total();
		    },
		    error: function(HttpRequest, textStatus, errorThrown) { 
		        //alert("Status: " + textStatus); alert("Error: " + errorThrown); 
		    }       
		}); 
		
	});
	
	function calculate_total(){
		var total=0;
		$('#cart_table tbody tr').each(function(){
			 var price = parseFloat($(this).find(".td_cart_price").html().replace(/\₹/g, '')).toFixed(2);
			 var quantity = parseFloat($(this).find('.cart_quant').val()).toFixed(2);
			 total += price*quantity;
			 
		});
		
		$('.cart_total').html('&#8377;'+parseFloat(total).toFixed(2));
	}
	
	</script>
{% endblock javascriptblock%}